<a href="https://colab.research.google.com/github/tranbuituanngoc/ML/blob/main/Lab_5_20130337_TranBuiTuanNgoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with **SVM** to classification tasks and compare its performance with other competitive algorithms. In general, **SVM** is one of the most popular and widely used supervised machine learning algorithms.

*   **Deadline: 23:59, 17/03/2023**



# Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import svm

In [2]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from prettytable import PrettyTable

#Task 1. 
For breast cancer dataset (https://tinyurl.com/3vme8hr3) which could be loaded from datasets in sklearn as follows:

```
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
cancer = datasets.load_breast_cancer()
```

*   1.1.	Apply SVM algorithm to above dataset using linear kernel.
*   1.2.	Compare the obtained results with other competitive algorithms (Logistic Regression, Decision Tree, kNN) based on metrics: accuracy, precision, recall, f1 measures.



In [3]:
# Import scikit-learn dataset library
from sklearn import datasets
# Load dataset
cancer = datasets.load_breast_cancer()

SVM

In [4]:
X= cancer['data']
Y= cancer['target']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf = svm.SVC(kernel='linear')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
kncm=confusion_matrix(y_test, y_pred)
knas=round(accuracy_score(y_test, y_pred),2)
knps=round(precision_score(y_test, y_pred),2)
knrs=round(recall_score(y_test, y_pred),2)
knfs=round(f1_score(y_test, y_pred),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred))
print ("Recall : ", recall_score(y_test, y_pred))
print ("F1 : ", f1_score(y_test, y_pred))

Confusion Matrix : 
 [[ 57   6]
 [  2 106]]
Accuracy :  0.9532163742690059
Precision :  0.9464285714285714
Recall :  0.9814814814814815
F1 :  0.9636363636363636


LogisticRegression

In [5]:
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
y_pred = clf.predict(X_test)
lras=round(accuracy_score(y_test, y_pred),2)
lrps=round(precision_score(y_test, y_pred),2)
lrrs=round(recall_score(y_test, y_pred),2)
lrfs=round(f1_score(y_test, y_pred),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[ 57   6]
 [  2 106]]
Accuracy :  0.9532163742690059
Precision :  0.9532163742690059
Recall :  0.9532163742690059
F1 :  0.9532163742690059


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTree

In [6]:
dtree = DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train) 
y_pred = dtree.predict(X_test)
y_pred = clf.predict(X_test)
dtcm=confusion_matrix(y_test, y_pred)
dtas=round(accuracy_score(y_test, y_pred),2)
dtps=round(precision_score(y_test, y_pred),2)
dtrs=round(recall_score(y_test, y_pred),2)
dtfs=round(f1_score(y_test, y_pred),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[ 57   6]
 [  2 106]]
Accuracy :  0.9532163742690059
Precision :  0.9532163742690059
Recall :  0.9532163742690059
F1 :  0.9532163742690059


kNN

In [7]:
cancer = KNeighborsClassifier()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
cancer.fit(X_train,y_train)
y_pred = cancer.predict(X_test) 
knncm=confusion_matrix(y_test, y_pred)
knnas=round(accuracy_score(y_test, y_pred),2)
knnps=round(precision_score(y_test, y_pred),2)
knnrs=round(recall_score(y_test, y_pred),2)
knnfs=round(f1_score(y_test, y_pred),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[ 56   7]
 [  5 103]]
Accuracy :  0.9298245614035088
Precision :  0.9298245614035088
Recall :  0.9298245614035088
F1 :  0.9298245614035088


In [8]:
t= PrettyTable(['Clasicfical Algorithm', 'Accuracy','Precision','Recall','F1'])
t.add_row(['SVM',knas,knps,knrs,knfs])
t.add_row(['kNN',knnas,knnps,knnrs,knnfs])
t.add_row(['DecisionTree',dtas,dtps,dtrs,dtfs])
t.add_row(['LogisticRegression',lras,lrps,lrrs,lrfs])
print(t)

+-----------------------+----------+-----------+--------+------+
| Clasicfical Algorithm | Accuracy | Precision | Recall |  F1  |
+-----------------------+----------+-----------+--------+------+
|          SVM          |   0.95   |    0.95   |  0.98  | 0.96 |
|          kNN          |   0.93   |    0.94   |  0.95  | 0.94 |
|      DecisionTree     |   0.95   |    0.95   |  0.98  | 0.96 |
|   LogisticRegression  |   0.95   |    0.95   |  0.98  | 0.96 |
+-----------------------+----------+-----------+--------+------+


#Task 2. 

*   1.1.	Perform SVM algorithm to **Iris dataset** using **linear kernel**.
*   1.2.	Compare the obtained results in 1.1 with SVM using other kernels (**Polynomial Kernel, Gaussian Kernel, Sigmoid Kernel, Radial Basis Function Kernel**). Some metrics could be used: accuracy, precision, recall, f1 measures





In [9]:
data4 = datasets.load_iris()

Polynomial Kernel

In [10]:
X= data4['data']
Y= data4['target']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf = svm.SVC(kernel='poly')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
plcm=confusion_matrix(y_test, y_pred)
plas=round(accuracy_score(y_test, y_pred),2)
plps=round(precision_score(y_test, y_pred, average='micro'),2)
plrs=round(recall_score(y_test, y_pred, average='micro'),2)
plfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]
Accuracy :  0.9777777777777777
Precision :  0.9777777777777777
Recall :  0.9777777777777777
F1 :  0.9777777777777777


Radial Basis




In [11]:
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
rbcm=confusion_matrix(y_test, y_pred)
rbas=round(accuracy_score(y_test, y_pred),2)
rbps=round(precision_score(y_test, y_pred, average='micro'),2)
rbrs=round(recall_score(y_test, y_pred, average='micro'),2)
rbfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]
Accuracy :  0.9777777777777777
Precision :  0.9777777777777777
Recall :  0.9777777777777777
F1 :  0.9777777777777777


Sigmoid Kernel

In [12]:
clf = svm.SVC(kernel='sigmoid')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
sias=round(accuracy_score(y_test, y_pred),2)
sips=round(precision_score(y_test, y_pred, average='micro'),2)
sirs=round(recall_score(y_test, y_pred, average='micro'),2)
sifs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[ 0  0 14]
 [ 0  0 18]
 [ 0  0 13]]
Accuracy :  0.28888888888888886
Precision :  0.28888888888888886
Recall :  0.28888888888888886
F1 :  0.28888888888888886


In [13]:
t= PrettyTable(['Liner Kernel', 'Accuracy','Precision','Recall','F1'])
t.add_row(['Sigmoid Kernel',sias,sips,sirs,sifs])
t.add_row(['Radial Basis',rbas,rbps,rbrs,rbfs])
t.add_row(['Polynomial Kernel',plas,plps,plrs,plfs])
print(t)

+-------------------+----------+-----------+--------+------+
|    Liner Kernel   | Accuracy | Precision | Recall |  F1  |
+-------------------+----------+-----------+--------+------+
|   Sigmoid Kernel  |   0.29   |    0.29   |  0.29  | 0.29 |
|    Radial Basis   |   0.98   |    0.98   |  0.98  | 0.98 |
| Polynomial Kernel |   0.98   |    0.98   |  0.98  | 0.98 |
+-------------------+----------+-----------+--------+------+


#Task 3. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with mnist dataset based on accuracy, precision, recall, f1 measures.


In [14]:
from sklearn import datasets
# load the MNIST digits dataset
mnist = datasets.load_digits()

SVM Sigmoid Kernel

In [15]:
X= mnist['data']
Y= mnist['target']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf = svm.SVC(kernel='sigmoid')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
sias=round(accuracy_score(y_test, y_pred),2)
sips=round(precision_score(y_test, y_pred, average='micro'),2)
sirs=round(recall_score(y_test, y_pred, average='micro'),2)
sifs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[55  0  0  0  4  0  0  0  0  0]
 [ 0 40  0  0  1  0  1  4  1  2]
 [ 0  2 46  0  0  0  0  0  1  0]
 [ 0  2  1 57  0  0  0  1  3  0]
 [ 2  3  0  0 55  0  1  0  0  0]
 [ 0  1  0  0  0 45  0  0  0  1]
 [ 0  0  0  0  1  0 50  0  0  0]
 [ 0  0  0  0  0  1  0 55  0  1]
 [ 0  2  1  1  0  1  0  0 35  6]
 [ 0  1  0  0  0  2  0  3  0 51]]
Accuracy :  0.9055555555555556
Precision :  0.9055555555555556
Recall :  0.9055555555555556
F1 :  0.9055555555555556


SVM Radial Basis

In [16]:
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
rbcm=confusion_matrix(y_test, y_pred)
rbas=round(accuracy_score(y_test, y_pred),2)
rbps=round(precision_score(y_test, y_pred, average='micro'),2)
rbrs=round(recall_score(y_test, y_pred, average='micro'),2)
rbfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[58  0  0  0  1  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  1 63  0  0  0  0  0  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  1  0  0  0  0  0  0 44  1]
 [ 0  0  0  0  0  2  0  0  0 55]]
Accuracy :  0.9851851851851852
Precision :  0.9851851851851852
Recall :  0.9851851851851852
F1 :  0.9851851851851852


SVM Polynomial Kernel

In [17]:
clf = svm.SVC(kernel='poly')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
plcm=confusion_matrix(y_test, y_pred)
plas=round(accuracy_score(y_test, y_pred),2)
plps=round(precision_score(y_test, y_pred, average='micro'),2)
plrs=round(recall_score(y_test, y_pred, average='micro'),2)
plfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[58  0  0  0  1  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  1 63  0  0  0  0  0  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  1  0  0  0  0  0  0 44  1]
 [ 0  0  0  0  0  2  0  0  0 55]]
Accuracy :  0.9851851851851852
Precision :  0.9851851851851852
Recall :  0.9851851851851852
F1 :  0.9851851851851852


Decision Tree

In [18]:
dtree = DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train) 
y_pred = dtree.predict(X_test)
y_pred = clf.predict(X_test)
dtcm=confusion_matrix(y_test, y_pred)
dtas=round(accuracy_score(y_test, y_pred),2)
dtps=round(precision_score(y_test, y_pred, average='micro'),2)
dtrs=round(recall_score(y_test, y_pred, average='micro'),2)
dtfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[58  0  0  0  1  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  1 63  0  0  0  0  0  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  1  0  0  0  0  0  0 44  1]
 [ 0  0  0  0  0  2  0  0  0 55]]
Accuracy :  0.9851851851851852
Precision :  0.9851851851851852
Recall :  0.9851851851851852
F1 :  0.9851851851851852


kNN

In [19]:
cancer = KNeighborsClassifier()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
cancer.fit(X_train,y_train)
y_pred = cancer.predict(X_test) 
knncm=confusion_matrix(y_test, y_pred)
knnas=round(accuracy_score(y_test, y_pred),2)
knnps=round(precision_score(y_test, y_pred, average='micro'),2)
knnrs=round(recall_score(y_test, y_pred, average='micro'),2)
knnfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[58  0  0  0  1  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 48  0  0  0  0  1  0  0]
 [ 0  0  0 64  0  0  0  0  0  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 57  0  0]
 [ 0  1  0  0  0  0  0  0 45  0]
 [ 0  0  0  0  0  1  0  0  0 56]]
Accuracy :  0.9907407407407407
Precision :  0.9907407407407407
Recall :  0.9907407407407407
F1 :  0.9907407407407407


LogisticRegression

In [20]:
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
y_pred = clf.predict(X_test)
lras=round(accuracy_score(y_test, y_pred),2)
lrps=round(precision_score(y_test, y_pred, average='micro'),2)
lrrs=round(recall_score(y_test, y_pred, average='micro'),2)
lrfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[58  0  0  0  1  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  1 63  0  0  0  0  0  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  1  0  0  0  0  0  0 44  1]
 [ 0  0  0  0  0  2  0  0  0 55]]
Accuracy :  0.9851851851851852
Precision :  0.9851851851851852
Recall :  0.9851851851851852
F1 :  0.9851851851851852


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
t= PrettyTable(['Liner Kernel', 'Accuracy','Precision','Recall','F1'])
t.add_row(['SVM Sigmoid Kernel',sias,sips,sirs,sifs])
t.add_row(['SVM Radial Basis',rbas,rbps,rbrs,rbfs])
t.add_row(['SVM Polynomial Kernel',plas,plps,plrs,plfs])
t.add_row(['kNN',knnas,knnps,knnrs,knnfs])
t.add_row(['DecisionTree',dtas,dtps,dtrs,dtfs])
t.add_row(['LogisticRegression',lras,lrps,lrrs,lrfs])
print(t)

+-----------------------+----------+-----------+--------+------+
|      Liner Kernel     | Accuracy | Precision | Recall |  F1  |
+-----------------------+----------+-----------+--------+------+
|   SVM Sigmoid Kernel  |   0.91   |    0.91   |  0.91  | 0.91 |
|    SVM Radial Basis   |   0.99   |    0.99   |  0.99  | 0.99 |
| SVM Polynomial Kernel |   0.99   |    0.99   |  0.99  | 0.99 |
|          kNN          |   0.99   |    0.99   |  0.99  | 0.99 |
|      DecisionTree     |   0.99   |    0.99   |  0.99  | 0.99 |
|   LogisticRegression  |   0.99   |    0.99   |  0.99  | 0.99 |
+-----------------------+----------+-----------+--------+------+


#Task 4. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with **credit card dataset** based on accuracy, precision, recall, f1 measures.

*   Give some comments on the obtained results
*   Identify issues with dataset, and propose the solutions to these issues



In [22]:
data=pd.read_csv('creditcard.csv')
X= data.iloc[1:50000, 1:-1]
Y= data.iloc[1:50000, -1]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)

SVM Sigmoid Kernel

In [23]:
clf = svm.SVC(kernel='sigmoid')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
sias=round(accuracy_score(y_test, y_pred),4)
sips=round(precision_score(y_test, y_pred, average='micro'),4)
sirs=round(recall_score(y_test, y_pred, average='micro'),4)
sifs=round(f1_score(y_test, y_pred, average='micro'),4)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14945     0]
 [   55     0]]
Accuracy :  0.9963333333333333
Precision :  0.9963333333333333
Recall :  0.9963333333333333
F1 :  0.9963333333333333


SVM Radial Basis

In [24]:
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
rbcm=confusion_matrix(y_test, y_pred)
rbas=round(accuracy_score(y_test, y_pred),4)
rbps=round(precision_score(y_test, y_pred, average='micro'),4)
rbrs=round(recall_score(y_test, y_pred, average='micro'),4)
rbfs=round(f1_score(y_test, y_pred, average='micro'),4)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14935    10]
 [   28    27]]
Accuracy :  0.9974666666666666
Precision :  0.9974666666666666
Recall :  0.9974666666666666
F1 :  0.9974666666666666


SVM Polynomial Kernel

In [25]:
clf = svm.SVC(kernel='poly')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
plcm=confusion_matrix(y_test, y_pred)
plas=round(accuracy_score(y_test, y_pred),4)
plps=round(precision_score(y_test, y_pred, average='micro'),4)
plrs=round(recall_score(y_test, y_pred, average='micro'),4)
plfs=round(f1_score(y_test, y_pred, average='micro'),4)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14945     0]
 [   51     4]]
Accuracy :  0.9966
Precision :  0.9966
Recall :  0.9966
F1 :  0.9966


Decision Tree

In [26]:
dtree = DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train) 
y_pred = dtree.predict(X_test)
y_pred = clf.predict(X_test)
dtcm=confusion_matrix(y_test, y_pred)
dtas=round(accuracy_score(y_test, y_pred),4)
dtps=round(precision_score(y_test, y_pred, average='micro'),4)
dtrs=round(recall_score(y_test, y_pred, average='micro'),4)
dtfs=round(f1_score(y_test, y_pred, average='micro'),4)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14945     0]
 [   51     4]]
Accuracy :  0.9966
Precision :  0.9966
Recall :  0.9966
F1 :  0.9966


kNN

In [27]:
cancer = KNeighborsClassifier()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
cancer.fit(X_train,y_train)
y_pred = cancer.predict(X_test) 
knncm=confusion_matrix(y_test, y_pred)
knnas=round(accuracy_score(y_test, y_pred),4)
knnps=round(precision_score(y_test, y_pred, average='micro'),4)
knnrs=round(recall_score(y_test, y_pred, average='micro'),4)
knnfs=round(f1_score(y_test, y_pred, average='micro'),4)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[14940     5]
 [   17    38]]
Accuracy :  0.9985333333333334
Precision :  0.9985333333333334
Recall :  0.9985333333333334
F1 :  0.9985333333333334


LogisticRegression

In [28]:
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
y_pred = clf.predict(X_test)
lras=round(accuracy_score(y_test, y_pred),4)
lrps=round(precision_score(y_test, y_pred, average='micro'),4)
lrrs=round(recall_score(y_test, y_pred, average='micro'),4)
lrfs=round(f1_score(y_test, y_pred, average='micro'),4)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Confusion Matrix : 
 [[14945     0]
 [   51     4]]
Accuracy :  0.9966
Precision :  0.9966
Recall :  0.9966
F1 :  0.9966


In [29]:
t= PrettyTable(['Liner Kernel', 'Accuracy','Precision','Recall','F1'])
t.add_row(['SVM Sigmoid Kernel',sias,sips,sirs,sifs])
t.add_row(['SVM Radial Basis',rbas,rbps,rbrs,rbfs])
t.add_row(['SVM Polynomial Kernel',plas,plps,plrs,plfs])
t.add_row(['kNN',knnas,knnps,knnrs,knnfs])
t.add_row(['DecisionTree',dtas,dtps,dtrs,dtfs])
t.add_row(['LogisticRegression',lras,lrps,lrrs,lrfs])
print(t)

+-----------------------+----------+-----------+--------+--------+
|      Liner Kernel     | Accuracy | Precision | Recall |   F1   |
+-----------------------+----------+-----------+--------+--------+
|   SVM Sigmoid Kernel  |  0.9963  |   0.9963  | 0.9963 | 0.9963 |
|    SVM Radial Basis   |  0.9975  |   0.9975  | 0.9975 | 0.9975 |
| SVM Polynomial Kernel |  0.9966  |   0.9966  | 0.9966 | 0.9966 |
|          kNN          |  0.9985  |   0.9985  | 0.9985 | 0.9985 |
|      DecisionTree     |  0.9966  |   0.9966  | 0.9966 | 0.9966 |
|   LogisticRegression  |  0.9966  |   0.9966  | 0.9966 | 0.9966 |
+-----------------------+----------+-----------+--------+--------+


#Finally,
Save a copy in your Github. Remember renaming the notebook.